name: Deploy Site with IndexNow

on:
  push:
    branches: ["main"]  # 根据你的默认分支名称调整
  schedule:
    - cron: '0 2 * * *'  # 每天北京时间上午10点运行
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.1'
          bundler-cache: true
          cache-version: 0

      - name: Generate IndexNow Key File
        run: echo ${{ secrets.INDEXNOW_KEY }} > ${{ secrets.INDEXNOW_KEY }}.txt

      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  indexnow:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Submit URLs via IndexNow
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://rizwiki.cn/sitemap.xml'  # 替换为你的实际URL
          key: ${{ secrets.INDEXNOW_KEY }}
          endpoint: 'api.indexnow.org'
          since: 1
          since-unit: 'day'
          failure-strategy: 'ignore'
